---
- name: Invoke Job Template in reponse to MQTT Messages
  hosts: all

  sources:
    - kubealex.eda.mqtt:
        host: "{{ mqtt_host }}"
        port: "{{ mqtt_port }}"
        topic: "{{ mqtt_topic }}"

  rules:
    - name: Run 'Scale Up K8s Service' Template
      condition: event.publish == true
      action:
        run_job_template:
          name: Scale Up K8s Service
          organization: Default
